version: '3.4'

services:
  trex.app.api:
    image: ${DOCKER_REGISTRY-}trexappapi
    build:
      context: ../
      dockerfile: TReX.App/TReX.App.Api/Dockerfile
    depends_on:
      - raven
      - event-store
  raven:
    image: "ravendb/ravendb"
    environment:
      RAVEN_Setup_Mode: "None"
      RAVEN_License: '{"Id":"43407100-48ab-4e93-b4b8-d72e0d4b9eb1","Name":"Razvan Radeanu","Keys":["L8ZuRaApksLivQ2leTbJJE9Cx","j2DhBpyr2h3v1sEw+U1VlV26+","m2p6yHJh+2IxVmFzLKanSd5nF","/Sw89hj4yWR0FLZR9SFPsOSrn","ltwW/lOijiy66XwfjFcq+Thot","+QRt+xgYp7OkP8aowXCcxOJH+","45aGvNWaf/Q3Lh3z9Sht9AAUE","oBQYHKEkDCgsMDQ4PEBFDBkQD","YmZQ"]}'
      RAVEN_License_Eula_Accepted: "true"
      RAVEN_Security_UnsecuredAccessAllowed: "PrivateNetwork"
      RAVEN_Port: 8081
      RAVEN_Url: "http://0.0.0.0:8081"
      RAVEN_TCP_Port: 38888
    ports:
        - "8081:8081"
  event-store:
    image: "eventstore/eventstore"
    environment:
      EVENTSTORE_RUN_PROJECTIONS: "All"
    ports:
      - "2113:2113"